// <auto-generated />
using CV.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CV.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("CV.Models.PanelAbout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NelerYapıyorumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NelerYapıyorumIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanıtım")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelAbouts");
                });

            modelBuilder.Entity("CV.Models.PanelEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("OkulAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulYıl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelEducations");
                });

            modelBuilder.Entity("CV.Models.PanelExperiance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DeneyimAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeneyimAlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeneyimIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeneyimYıl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelExperiances");
                });

            modelBuilder.Entity("CV.Models.PanelProfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Github")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonumAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeslekAlanı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelProfils");
                });

            modelBuilder.Entity("CV.Models.PanelProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BlogAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogResim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
